# Generated by Django 3.0.3 on 2020-04-12 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import html_form.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=64)),
                ('line_two', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('county', models.CharField(choices=[('Bath and North East Somerset', 'Bath and North East Somerset'), ('Bedford', 'Bedford'), ('Berkshire', 'Berkshire'), ('Blackburn with Darwen', 'Blackburn with Darwen'), ('Blackpool', 'Blackpool'), ('Bournemouth', 'Bournemouth'), ('Brighton & Hove', 'Brighton & Hove'), ('Bristol', 'Bristol'), ('Buckinghamshire', 'Buckinghamshire'), ('Cambridgeshire', 'Cambridgeshire'), ('Central Bedfordshire', 'Central Bedfordshire'), ('Cheshire East', 'Cheshire East'), ('Cheshire West and Chester', 'Cheshire West and Chester'), ('Cornwall', 'Cornwall'), ('Cumbria', 'Cumbria'), ('Darlington', 'Darlington'), ('Derby', 'Derby'), ('Derbyshire', 'Derbyshire'), ('Devon', 'Devon'), ('Dorset', 'Dorset'), ('Durham', 'Durham'), ('East Riding of Yorkshire', 'East Riding of Yorkshire'), ('East Sussex', 'East Sussex'), ('Essex', 'Essex'), ('Gloucestershire', 'Gloucestershire'), ('Greater Manchester', 'Greater Manchester'), ('Halton', 'Halton'), ('Hampshire', 'Hampshire'), ('Hartlepool', 'Hartlepool'), ('Herefordshire', 'Herefordshire'), ('Hertfordshire', 'Hertfordshire'), ('Isle of Wight', 'Isle of Wight'), ('Kent', 'Kent'), ('Kingston upon Hull', 'Kingston upon Hull'), ('Lancashire', 'Lancashire'), ('Leicester', 'Leicester'), ('Leicestershire', 'Leicestershire'), ('Lincolnshire', 'Lincolnshire'), ('London', 'London'), ('Luton', 'Luton'), ('Medway', 'Medway'), ('Merseyside', 'Merseyside'), ('Middlesbrough', 'Middlesbrough'), ('Milton Keynes', 'Milton Keynes'), ('Norfolk', 'Norfolk'), ('North East Lincolnshire', 'North East Lincolnshire'), ('North Lincolnshire', 'North Lincolnshire'), ('North Somerset', 'North Somerset'), ('North Yorkshire', 'North Yorkshire'), ('Northamptonshire', 'Northamptonshire'), ('Northumberland', 'Northumberland'), ('Nottingham', 'Nottingham'), ('Nottinghamshire', 'Nottinghamshire'), ('Oxfordshire', 'Oxfordshire'), ('Peterborough', 'Peterborough'), ('Plymouth', 'Plymouth'), ('Poole', 'Poole'), ('Portsmouth', 'Portsmouth'), ('Redcar and Cleveland', 'Redcar and Cleveland'), ('Rutland', 'Rutland'), ('Shropshire', 'Shropshire'), ('Somerset', 'Somerset'), ('South Gloucestershire', 'South Gloucestershire'), ('South Yorkshire', 'South Yorkshire'), ('Southampton', 'Southampton'), ('Southend-on-Sea', 'Southend-on-Sea'), ('Staffordshire', 'Staffordshire'), ('Stockton-on-Tees', 'Stockton-on-Tees'), ('Stoke-on-Trent', 'Stoke-on-Trent'), ('Suffolk', 'Suffolk'), ('Surrey', 'Surrey'), ('Swindon', 'Swindon'), ('Telford and Wrekin', 'Telford and Wrekin'), ('Thurrock', 'Thurrock'), ('Torbay', 'Torbay'), ('Tyne and Wear', 'Tyne and Wear'), ('Warrington', 'Warrington'), ('Warwickshire', 'Warwickshire'), ('West Midlands', 'West Midlands'), ('West Sussex', 'West Sussex'), ('West Yorkshire', 'West Yorkshire'), ('Wiltshire', 'Wiltshire'), ('Worcestershire', 'Worcestershire'), ('York', 'York'), ('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Down', 'Down'), ('Fermanagh', 'Fermanagh'), ('Londonderry', 'Londonderry'), ('Tyrone', 'Tyrone'), ('Blaenau Gwent', 'Blaenau Gwent'), ('Bridgend', 'Bridgend'), ('Caerphilly', 'Caerphilly'), ('Cardiff', 'Cardiff'), ('Carmarthenshire', 'Carmarthenshire'), ('Ceredigion', 'Ceredigion'), ('Conwy', 'Conwy'), ('Denbighshire', 'Denbighshire'), ('Flintshire', 'Flintshire'), ('Gwynedd', 'Gwynedd'), ('Isle of Anglesey', 'Isle of Anglesey'), ('Merthyr Tydfil', 'Merthyr Tydfil'), ('Monmouthshire', 'Monmouthshire'), ('Neath Port Talbot', 'Neath Port Talbot'), ('Newport', 'Newport'), ('Pembrokeshire', 'Pembrokeshire'), ('Powys', 'Powys'), ('Rhondda Cynon Taf', 'Rhondda Cynon Taf'), ('Swansea', 'Swansea'), ('Torfaen', 'Torfaen'), ('Vale of Glamorgan', 'Vale of Glamorgan'), ('Wrexham', 'Wrexham'), ('Aberdeen City', 'Aberdeen City'), ('Aberdeenshire', 'Aberdeenshire'), ('Angus', 'Angus'), ('Argyll and Bute', 'Argyll and Bute'), ('Clackmannanshire', 'Clackmannanshire'), ('Dumfries and Galloway', 'Dumfries and Galloway'), ('Dundee City', 'Dundee City'), ('East Ayrshire', 'East Ayrshire'), ('East Dunbartonshire', 'East Dunbartonshire'), ('East Lothian', 'East Lothian'), ('East Renfrewshire', 'East Renfrewshire'), ('Edinburgh, City of ', 'Edinburgh, City of'), ('Falkirk', 'Falkirk'), ('Fife', 'Fife'), ('Glasgow City', 'Glasgow City'), ('Highland', 'Highland'), ('Inverclyde', 'Inverclyde'), ('Midlothian', 'Midlothian'), ('Moray', 'Moray'), ('North Ayrshire', 'North Ayrshire'), ('North Lanarkshire', 'North Lanarkshire'), ('Perth and Kinross', 'Perth and Kinross'), ('Renfrewshire', 'Renfrewshire'), ('Scottish Borders', 'Scottish Borders'), ('South Ayrshire', 'South Ayrshire'), ('South Lanarkshire', 'South Lanarkshire'), ('Stirling', 'Stirling'), ('West Dunbartonshire', 'West Dunbartonshire'), ('West Lothian', 'West Lothian'), ('Na h-Eileanan Siar', 'Na h-Eileanan Siar'), ('Orkney Islands', 'Orkney Islands'), ('Shetland Islands', 'Shetland Islands')], max_length=64)),
                ('postcode', models.CharField(max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('address_type', models.CharField(choices=[('BILL', 'Billing'), ('JOB', 'Job')], default='JOB', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64, validators=[html_form.validators.validate_alpha])),
                ('last', models.CharField(max_length=64, validators=[html_form.validators.validate_alpha])),
                ('email', models.EmailField(max_length=64, validators=[django.core.validators.EmailValidator()])),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ManyToManyField(related_name='address', to='html_form.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('IN', 'Inbox'), ('CU', 'Current'), ('AR', 'Archive')], default='IN', max_length=2)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='html_form.Address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='html_form.Person')),
                ('job_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_address', to='html_form.Address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ManyToManyField(related_name='owner', to='html_form.Person'),
        ),
    ]
