# Generated by Django 3.0.3 on 2020-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_form', '0002_job_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
