# Generated by Django 3.0.3 on 2020-03-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('html_form', '0008_auto_20200313_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='address',
        ),
        migrations.AddField(
            model_name='job',
            name='billing_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='html_form.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='job_address', to='html_form.Address'),
            preserve_default=False,
        ),
    ]
