# Generated by Django 3.0.3 on 2020-03-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('html_form', '0010_auto_20200316_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ManyToManyField(related_name='owner', to='html_form.Client'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='html_form.Client'),
        ),
    ]
