# Generated by Django 3.0.3 on 2020-04-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_form', '0011_auto_20200318_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
    ]
