# Generated by Django 3.0.3 on 2020-04-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_form', '0013_auto_20200406_1242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Person',
        ),
    ]
