# Generated by Django 3.0.3 on 2020-04-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_form', '0014_auto_20200406_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('BILL', 'Billing'), ('JOB', 'Job')], default='JOB', max_length=4),
        ),
    ]
